# Day 3: NumPy - Numerical Excellence 

We move into **NumPy** (Numerical Python), which is the foundation of almost all Machine Learning libraries in Python.

### Why NumPy?
- It's much faster than regular Python lists.
- It supports **vectorization** (performing operations on entire arrays at once).
- It's the core of Scikit-Learn, Pandas, and TensorFlow.

### Topics Covered:
1. **Creating Arrays**
2. **Array Attributes** (Shape, Size, Type)
3. **Indexing & Slicing**
4. **Vectorized Operations**
5. **Mini Project: Matrix Math & Linear Equations**

## 1. Creating Arrays
First, we need to import NumPy. Conventionally, it is imported as `np`.

In [8]:
import numpy as np

# Creating a 1D array from a list
arr_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D array (Matrix)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Special arrays
zeros = np.zeros((2, 3))       # 2x3 matrix of zeros
ones = np.ones((3, 2))        # 3x2 matrix of ones
identity = np.eye(3)          # 3x3 Identity matrix
random = np.random.rand(2, 2) # 2x2 matrix of random numbers

print("1D Array:", arr_1d)
print("2D Array:\n", arr_2d)
print("Identity Matrix:\n", identity)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
import numpy as np
zeros = np.eye(4)  
print(zeros)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2. Array Attributes
Understanding the structure of your data.

In [ ]:
print(f"Shape of arr_2d: {arr_2d.shape}") # (rows, columns)
print(f"Number of dimensions: {arr_2d.ndim}") # 2
print(f"Data type: {arr_2d.dtype}") # int64
print(f"Total elements: {arr_2d.size}") # 6

In [12]:
print(arr_2d.size)

6


## 3. Indexing and Slicing
Accessing specific parts of the array.

In [13]:
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("Original Matrix:\n", data)

# Accessing a single element (row 1, col 2 -> 60)
print(f"Element at [1, 2]: {data[1, 2]}")

# Slicing: First two rows
print("First two rows:\n", data[:2, :])

# Slicing: Last column
print("Last column:", data[:, -1])

Original Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Element at [1, 2]: 60
First two rows:
 [[10 20 30]
 [40 50 60]]
Last column: [30 60 90]


## 4. Vectorized Operations
No more 'for' loops for math!

In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(f"Addition: {x + y}")
print(f"Scalar Multiplication: {x * 10}")
print(f"Square root: {np.sqrt(x)}")
print(f"Dot Product: {np.dot(x, y)}")

Addition: [5 7 9]
Scalar Multiplication: [10 20 30]
Square root: [1.         1.41421356 1.73205081]
Dot Product: 32


## 5. Mini Project: Solving Linear Equations
Let's solve the system:
1. `2x + 3y = 8`
2. `5x - y = 3`

In matrix form: `AX = B` -> `X = A_inverse * B`

In [15]:
# Coefficients (A)
A = np.array([[2, 3], [5, -1]])

# Constants (B)
B = np.array([8, 3])

# Solving for X
solution = np.linalg.solve(A, B)

print(f"Solution: x = {solution[0]:.2f}, y = {solution[1]:.2f}")

# Verifying the result (A * solution should equal B)
print(f"Verification: {np.allclose(np.dot(A, solution), B)}")

Solution: x = 1.00, y = 2.00
Verification: True
